Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -1,4 +1,4 @@
-name: Lint with Pylint
+name: Pylint
 on:
   push:
     branches: ["main"]
@@ -26,19 +26,32 @@ jobs:
         python -m pip install --upgrade pip
         pip install pylint
         if [ -f flask-server/requirements.txt ]; then pip install -r flask-server/requirements.txt; fi
-
+        
     - name: Analysing the code with pylint
+      id: pylint
       run: |
-        pylint_result=$(pylint $(git ls-files '*.py'))
-        pylint_exit_code=$?
+        # List all Python files
+        all_python_files=$(git ls-files '*.py')
 
-        echo "Pylint result: $pylint_result"
-        echo "Pylint exit code: $pylint_exit_code"
+        # Filter out test files
+        filtered_files=$(echo "$all_python_files" | grep -v -e 'test_.*\.py')
 
-        # Check if there are fatal (1), error (2), or usage error (32) messages
-        if [ $((pylint_exit_code & (1 | 2 | 32))) -ne 0 ]; then
-          echo "Pylint found fatal, error, or usage errors. Exiting with code $pylint_exit_code."
-          exit $pylint_exit_code
+        if [[ -z "$filtered_files" ]]; then
+          echo "No Python files to lint."
         else
-          echo "Pylint passed successfully."
+          pylint_result=$(pylint $filtered_files 2>&1)
+          pylint_exit_code=$?
+
+          echo "Pylint result: $pylint_result"
+          echo "Pylint exit code: $pylint_exit_code"
+
+          # Check if there are fatal (1), error (2), or usage error (32) messages
+          if [ $((pylint_exit_code & (1 | 2 | 32))) -ne 0 ]; then
+            echo "Pylint found fatal, error, or usage errors. Exiting with code $pylint_exit_code."
+            echo "Pylint output:"
+            echo "$pylint_result"
+            exit $pylint_exit_code
+          else
+            echo "Pylint passed successfully."
+          fi
         fi
