Update pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -1,27 +1,44 @@
-name: Pylint
-
+name: Lint with Pylint
 on:
   push:
-      branches: ["main"]
+    branches: ["main"]
   pull_request:
-      branches: ["main"]
+    branches: ["main"]
 
 jobs:
   build:
     runs-on: ubuntu-latest
+
     strategy:
       matrix:
         python-version: ["3.10", "3.11", "3.12"]
+
     steps:
     - uses: actions/checkout@v4
+
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pylint
+        if [ -f flask-server/requirements.txt ]; then pip install -r flask-server/requirements.txt; fi
+
     - name: Analysing the code with pylint
       run: |
-        pylint $(git ls-files '*.py')
+        pylint_result=$(pylint $(git ls-files '*.py'))
+        pylint_exit_code=$?
+
+        echo "Pylint result: $pylint_result"
+        echo "Pylint exit code: $pylint_exit_code"
+
+        # Check if there are fatal (1), error (2), or usage error (32) messages
+        if [ $((pylint_exit_code & (1 | 2 | 32))) -ne 0 ]; then
+          echo "Pylint found fatal, error, or usage errors. Exiting with code $pylint_exit_code."
+          exit $pylint_exit_code
+        else
+          echo "Pylint passed successfully."
+        fi
